name: Variables and Secrets for Repositories
on: [push]

jobs:
  log-vars:
    runs-on: ${{ vars.JOBS_RUNNER }}
    env:
      BOOLEAN_SECRET: ${{ secrets.BOOLEAN_SECRET }}
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
      ENV_LEVEL_VAR2: ${{ vars.ENV_LEVEL_VAR2 }}
      ENV_LEVEL_VAR3: ${{ vars.ENV_LEVEL_VAR3 }}
    steps:
      - name: Run only if BOOLEAN_SECRET is true
        if: env.BOOLEAN_SECRET == 'true'
        run: echo "El secreto era verdadero"
      - name: Log Vars
        run: |
          echo '${{ vars.JOBS_RUNNER }}'
          echo "ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
          echo "ENV_LEVEL_VAR2: ${{ vars.ENV_LEVEL_VAR2 }}
          echo "ENV_LEVEL_VAR3: ${{ vars.ENV_LEVEL_VAR3 }}